// GENERATED by tools/build-audio.mjs — do not edit by hand.
// Sprite offsets into assets/audio/sfx.wav, and the takes available per sound.

export const SPRITE = {
    carbine_1: [
        0,
        191
    ],
    carbine_2: [
        221,
        201
    ],
    carbine_3: [
        451,
        182
    ],
    shotgun_1: [
        664,
        278
    ],
    shotgun_2: [
        972,
        278
    ],
    shotgun_3: [
        1280,
        298
    ],
    mg_1: [
        1609,
        167
    ],
    mg_2: [
        1806,
        166
    ],
    mg_3: [
        2002,
        168
    ],
    dmr_1: [
        2199,
        320
    ],
    dmr_2: [
        2549,
        321
    ],
    dmr_3: [
        2900,
        336
    ],
    pdw_1: [
        3267,
        158
    ],
    pdw_2: [
        3454,
        156
    ],
    pdw_3: [
        3640,
        154
    ],
    grenadeThrow_1: [
        3824,
        191
    ],
    grenadeThrow_2: [
        4045,
        192
    ],
    explosion_1: [
        4267,
        730
    ],
    explosion_2: [
        5028,
        703
    ],
    impact_1: [
        5761,
        44
    ],
    impact_2: [
        5835,
        47
    ],
    impact_3: [
        5912,
        47
    ],
    hit_1: [
        5989,
        74
    ],
    hit_2: [
        6093,
        77
    ],
    hit_3: [
        6200,
        75
    ],
    down_1: [
        6305,
        373
    ],
    down_2: [
        6708,
        383
    ],
    breachStart_1: [
        7121,
        207
    ],
    breachStart_2: [
        7358,
        203
    ],
    breach_1: [
        7590,
        333
    ],
    breach_2: [
        7953,
        326
    ],
    revive: [
        8310,
        339
    ],
    select: [
        8679,
        44
    ],
    order: [
        8752,
        54
    ],
    pause: [
        8837,
        102
    ],
    unpause: [
        8968,
        101
    ],
    win: [
        9099,
        710
    ],
    suppressed_1: [
        9839,
        146
    ],
    suppressed_2: [
        10015,
        150
    ],
    suppressed_3: [
        10195,
        140
    ],
    reload_1: [
        10365,
        686
    ],
    reload_2: [
        11081,
        687
    ],
    smokePop_1: [
        11798,
        721
    ],
    smokePop_2: [
        12549,
        712
    ],
    flashBang_1: [
        13291,
        781
    ],
    flashBang_2: [
        14102,
        785
    ],
    charge_1: [
        14917,
        358
    ],
    charge_2: [
        15305,
        348
    ],
    alarm: [
        15683,
        623
    ],
    objective: [
        16336,
        306
    ],
    lose: [
        16672,
        923
    ]
};

export const VARIANTS = {
    carbine: [
        "carbine_1",
        "carbine_2",
        "carbine_3"
    ],
    shotgun: [
        "shotgun_1",
        "shotgun_2",
        "shotgun_3"
    ],
    mg: [
        "mg_1",
        "mg_2",
        "mg_3"
    ],
    dmr: [
        "dmr_1",
        "dmr_2",
        "dmr_3"
    ],
    pdw: [
        "pdw_1",
        "pdw_2",
        "pdw_3"
    ],
    grenadeThrow: [
        "grenadeThrow_1",
        "grenadeThrow_2"
    ],
    explosion: [
        "explosion_1",
        "explosion_2"
    ],
    impact: [
        "impact_1",
        "impact_2",
        "impact_3"
    ],
    hit: [
        "hit_1",
        "hit_2",
        "hit_3"
    ],
    down: [
        "down_1",
        "down_2"
    ],
    breachStart: [
        "breachStart_1",
        "breachStart_2"
    ],
    breach: [
        "breach_1",
        "breach_2"
    ],
    revive: [
        "revive"
    ],
    select: [
        "select"
    ],
    order: [
        "order"
    ],
    pause: [
        "pause"
    ],
    unpause: [
        "unpause"
    ],
    win: [
        "win"
    ],
    suppressed: [
        "suppressed_1",
        "suppressed_2",
        "suppressed_3"
    ],
    reload: [
        "reload_1",
        "reload_2"
    ],
    smokePop: [
        "smokePop_1",
        "smokePop_2"
    ],
    flashBang: [
        "flashBang_1",
        "flashBang_2"
    ],
    charge: [
        "charge_1",
        "charge_2"
    ],
    alarm: [
        "alarm"
    ],
    objective: [
        "objective"
    ],
    lose: [
        "lose"
    ]
};
